project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

pull_request_title: Update translations
commit_message: Update translations (%language%)
append_commit_message: false

files:
  - source: /locales/en/*.json
    translation: /locales/%locale%/%original_file_name%
