name: Crowdin Sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  crowdin-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: ${{ github.repository_owner == 'linearmouse' }}
        uses: actions/checkout@v2

      - name: Crowdin sync
        if: ${{ github.repository_owner == 'linearmouse' }}
        uses: crowdin/github-action@1.4.10
        with:
          upload_translations: true
          download_translations: true
          commit_message: Update translations (%language%)

          localization_branch_name: l10n_crowdin_action
          create_pull_request: true
          pull_request_title: Update translations
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
